//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JBNClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsView
    {
        public int ItemID { get; set; }
        public int ChildCategoryID { get; set; }
        public int CategoryProductID { get; set; }
        public int SubCategoryID { get; set; }
        public string SubCategoryName { get; set; }
        public string MainCategoryName { get; set; }
        public string ItemName { get; set; }
        public string ChildCategoryName { get; set; }
    }
}
