//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JBNClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdvertisementNationSlot
    {
        public int ID { get; set; }
        public string Nation { get; set; }
        public System.DateTime Date { get; set; }
        public string Slots { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> BrandID { get; set; }
        public int TypeOfAdvertisementID { get; set; }
        public int AdvertisementAreaID { get; set; }
        public int TimeSlotId { get; set; }
        public int ProductID { get; set; }
    }
}
