//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JBNClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdminSetting
    {
        public int ID { get; set; }
        public Nullable<int> AddDaysForSearch { get; set; }
        public Nullable<int> AdDurationInSeconds { get; set; }
        public Nullable<int> MaxDurationsAllowedPerHr { get; set; }
        public Nullable<int> HoursOfExpiry { get; set; }
        public Nullable<double> WeekendMatrix { get; set; }
        public Nullable<int> FestDays { get; set; }
        public Nullable<int> SetPaymentDueinHrs { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int ContentExpiryinHrs { get; set; }
    }
}
