//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JBNClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdTracker
    {
        public int ID { get; set; }
        public Nullable<int> AdvertisementMainId { get; set; }
        public Nullable<int> NationId { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> SlotNumber { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<System.DateTime> AdStartDate { get; set; }
        public Nullable<int> Iterations { get; set; }
        public string AdType { get; set; }
        public Nullable<int> TimeSlotID { get; set; }
        public string Slots { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsLastEntryState { get; set; }
        public bool IsLastEntryDistrict { get; set; }
        public bool IsActive { get; set; }
    }
}
