//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JBNClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdvertisementCity
    {
        public int ID { get; set; }
        public Nullable<int> AdvertisementID { get; set; }
        public Nullable<int> AdvertisementMainID { get; set; }
        public Nullable<int> StateWithCityID { get; set; }
        public Nullable<int> TairTypeOfCityID { get; set; }
        public string TairTypeOfCity { get; set; }
        public string VillageLocalityName { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual tblAdvertisementMain tblAdvertisementMain { get; set; }
        public virtual tblStateWithCity tblStateWithCity { get; set; }
        public virtual tblTairTypeOfCity tblTairTypeOfCity { get; set; }
    }
}
