//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JBNClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCategoryProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCategoryProduct()
        {
            this.tblCategoryProductWithCusts = new HashSet<tblCategoryProductWithCust>();
            this.tblSubCategoryProductWithCusts = new HashSet<tblSubCategoryProductWithCust>();
        }
    
        public int ID { get; set; }
        public int CategoryProductID { get; set; }
        public string MainCategoryName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> BusinessTypeID { get; set; }
        public string RefferedByOrReason { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<bool> IsMasterProduct { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsRejected { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCategoryProductWithCust> tblCategoryProductWithCusts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSubCategoryProductWithCust> tblSubCategoryProductWithCusts { get; set; }
    }
}
