//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JBNClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCategoryHistory
    {
        public int ID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductCategory { get; set; }
        public string MainCategory { get; set; }
        public string SubCategory { get; set; }
        public string ChildCategory { get; set; }
        public string OldProductName { get; set; }
        public string OldMainCategory { get; set; }
        public string OldSubCategory { get; set; }
        public string OldChildCategory { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual tblUser tblUser { get; set; }
        public virtual tblItemCategory tblItemCategory { get; set; }
    }
}
