//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JBNClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFormPermissionItem
    {
        public int ID { get; set; }
        public Nullable<int> FormPermissionID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> SubMenuID { get; set; }
        public Nullable<int> MainMenuID { get; set; }
        public Nullable<bool> IsCreate { get; set; }
        public Nullable<bool> IsView { get; set; }
        public Nullable<bool> IsEdit { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual tblFormPermission tblFormPermission { get; set; }
        public virtual tblSysRole tblSysRole { get; set; }
    }
}
