//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JBNClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPayment
    {
        public int ID { get; set; }
        public int AdvertisementMainID { get; set; }
        public Nullable<int> CustID { get; set; }
        public string TxnID { get; set; }
        public string TxnStatusCode { get; set; }
        public string OrderID { get; set; }
        public Nullable<double> OrderAmount { get; set; }
        public string TxnStatusMessage { get; set; }
        public string TxnStatus { get; set; }
        public string PreAuthID { get; set; }
        public string txnPaymentMode { get; set; }
        public string txnSignature { get; set; }
        public string txnType { get; set; }
        public string txnTime { get; set; }
        public string txnReferenceID { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual tblAdvertisementMain tblAdvertisementMain { get; set; }
        public virtual tblCustomerDetail tblCustomerDetail { get; set; }
        public virtual tblCustomerDetail tblCustomerDetail1 { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
