//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JBNClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPushNotification
    {
        public int ID { get; set; }
        public Nullable<int> CustID { get; set; }
        public Nullable<System.DateTime> NotificationDate { get; set; }
        public string PushNotification { get; set; }
        public string Title { get; set; }
        public string CategoryName { get; set; }
        public string ImageURL { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsRead { get; set; }
        public Nullable<int> QueryID { get; set; }
        public string NotificationType { get; set; }
    
        public virtual tblCustomerDetail tblCustomerDetail { get; set; }
    }
}
