//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JBNClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblselectedDealer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblselectedDealer()
        {
            this.tblDeleteChats = new HashSet<tblDeleteChat>();
            this.tblDeleteConversations = new HashSet<tblDeleteConversation>();
            this.tblDeleteEnquiries = new HashSet<tblDeleteEnquiry>();
            this.tblFavoriteConversations = new HashSet<tblFavoriteConversation>();
            this.tblSelectedDealerBusinessTypes = new HashSet<tblSelectedDealerBusinessType>();
            this.tblselectedDealerDetails = new HashSet<tblselectedDealerDetail>();
            this.tblUserConversations = new HashSet<tblUserConversation>();
        }
    
        public int ID { get; set; }
        public int CustID { get; set; }
        public Nullable<int> CityId { get; set; }
        public string FirmName { get; set; }
        public string MNumber { get; set; }
        public string BusinessDemand { get; set; }
        public string PurposeBusiness { get; set; }
        public string OpenText { get; set; }
        public string replayText { get; set; }
        public string Image { get; set; }
        public string Image1 { get; set; }
        public Nullable<System.DateTime> LastUpdatedMsgDate { get; set; }
        public Nullable<int> IsRead { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> BusinessDemandID { get; set; }
        public Nullable<int> ProfessionalRequirementID { get; set; }
        public Nullable<bool> IsAdEnquiry { get; set; }
        public string EnquiryType { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual tblBusinessDemand tblBusinessDemand { get; set; }
        public virtual tblCustomerDetail tblCustomerDetail { get; set; }
        public virtual tblCustomerDetail tblCustomerDetail1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDeleteChat> tblDeleteChats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDeleteConversation> tblDeleteConversations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDeleteEnquiry> tblDeleteEnquiries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFavoriteConversation> tblFavoriteConversations { get; set; }
        public virtual tblItemCategory tblItemCategory { get; set; }
        public virtual tblProfessionalRequirement tblProfessionalRequirement { get; set; }
        public virtual tblStateWithCity tblStateWithCity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSelectedDealerBusinessType> tblSelectedDealerBusinessTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblselectedDealerDetail> tblselectedDealerDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserConversation> tblUserConversations { get; set; }
    }
}
