//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JBNClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblselectedDealerDetail
    {
        public int ID { get; set; }
        public Nullable<int> QueryId { get; set; }
        public Nullable<int> CustID { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<System.DateTime> LastUpdatedMsgDate { get; set; }
        public Nullable<int> IsRead { get; set; }
        public Nullable<int> SenderID { get; set; }
        public Nullable<int> IsFavorite { get; set; }
        public string FavoriteCustID { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public string DeletedCustID { get; set; }
        public Nullable<int> SenderRead { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual tblCustomerDetail tblCustomerDetail { get; set; }
        public virtual tblCustomerDetail tblCustomerDetail1 { get; set; }
        public virtual tblselectedDealer tblselectedDealer { get; set; }
        public virtual tblStateWithCity tblStateWithCity { get; set; }
    }
}
